### PR TITLE
 Add option to update unchanged states

### PR DESCRIPTION
**Pull request by lvogt**
This is useful with "unchanged" logging and no explicit interval, so values get always saved when they are fetched.

This is basically identical to my modbus commit...

EDIT: Aaaah sorry. I didn't want to create the PR. Due to moving some stuff around, this is *not* tested.
It should work, but I am not completely sure. I will report back tomorrow.

### CODE REVIEW

**Comment by Apollon77** [comment]
This pull request **introduces 1 alert** when merging 39ad71b3d0f2122ff93999cc4430cbe18900dad5 into fb3d0cf5f9d61df848a61bd77c8773ce8aaced6d - [view on LGTM.com](https://lgtm.com/projects/g/Apollon77/ioBroker.mbus/rev/pr-d57890e281a6b5a953315e821814dfcad03d0fdc)

**new alerts:**

* 1 for Conflicting HTML element attributes

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Apollon77** [comment]
No problem, test and I will also check it afterwards. Thank you!

**Comment by lvogt** [comment]
Patch seems to work fine here :)

**Comment by Apollon77** [comment]
alwaysUpdate shuld aoso be defined with default value in io-package.json

**Comment by Apollon77** [comment]
thank you, will come into 2.0.0

**Pull request merged**
